/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/niwa.theme.ts
 * Command: astryx theme build src/theme/niwa.theme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const niwaTheme: DefinedTheme;
